### ISSUE TITLE
Request to integrate XLMOD obo ontology into OLS

### ISSUE THREAD

**Issue by nilshoffmann** [EBISPOT/OLS#210]
Hi,
as part of the semantic validation for mzTab for metabolomics project, we need to be able to resolve parent <-> child relationship queries for the PSI XLMOD ontology:
https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/cv/XLMOD.obo
in OLS.

Is this possible to integrate it into OLS and would there be a timeline for it?
Our tracking issue is here:
https://github.com/HUPO-PSI/mzTab/issues/151

**Comment by simonjupp** [comment]
Hi, 
Yes we are happy to add this. The metadata for OLS is captured in the YAML config below, please check and modify accordingly (OLS does a conversion from OBO to OWL before loading, so your definition, synonym, and part of property need to be URIs, I've checked and these are the correct URIs you need). 

For GDPR compliance we now request that any additions to OLS need to come through ols-submission@ebi.ac.uk. OLS requires the limited processing of your personal data in order to function. By using the service you are agreeing to this as outlined in our Submission Privacy Notice, https://www.ebi.ac.uk/data-protection/privacy-notice/ols. 

```
  - id: xlmod
    preferredPrefix: XLMOD
    title: PSI XLMOD ontology
    uri: http://purl.obolibrary.org/obo/XLMOD.obo
    description: "cross-linking reagents, cross-linker related post-translational modifications, and derivatization reagents for GC-MS"
    homepage: https://github.com/HUPO-PSI/mzTab
    mailing_list: https://github.com/HUPO-PSI/mzTab/issues
    definition_property:
      - http://purl.obolibrary.org/obo/def
    synonym_property:
      - http://www.geneontology.org/formats/oboInOWL#hasExactSynonym
    base_uri:
      - http://purl.obolibrary.org/obo/xlmod_
    hierarchical_property:
      - http://purl.obolibrary.org/obo/XLMOD.obo#part_of
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/cv/XLMOD.obo
```
