### ISSUE TITLE
Adding SDGIO to the OLS

### ISSUE THREAD

**Issue by pbuttigieg** [EBISPOT/OLS#215]
Dear OLS team,

In collaboration with UN Environment, we've created an ontology for the Sustainable Development Goals and surrounding phenomena. We'd very much appreciate its inclusion in the OLS.

The ontology is built along OBO best practices, but doesn't use OBO PURLs.
Emulating #210, I've added some metadata below. The hierarchical property may be malformed, but we just use `rdfs:subClassOf` for the backbone. 

Please let me know if you need more information or have any queries.

```
id: sdgio
    preferredPrefix: SDGIO
    title: Sustainable Development Goals Interface Ontology
    uri: http://purl.unep.org/sdg/sdgio.owl
    description: "An OBO-compliant ontology representing the entities referenced by the SDGs, their targets, and indicators."
    homepage: https://github.com/SDG-InterfaceOntology/sdgio
    mailing_list: https://github.com/SDG-InterfaceOntology/sdgio/issues
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOWL#hasExactSynonym
    base_uri:
      - http://purl.unep.org/sdg/SDGIO_
    hierarchical_property:
      - rdfs:subClassOf
    oboSlims: false
    ontology_purl: http://purl.unep.org/sdg/sdgio.owl
```
