### ISSUE TITLE
Indexer changes ontology IRI

### ISSUE THREAD

**Issue by neobernad** [EBISPOT/OLS#240]
Hello,

I am running a local installation of OLS, whenever I run the indexer (`ols-indexer.jar`) it changes the IRI field in the MongoDB to `http://purl.obolibrary.org/obo/` format. For instance, my ols-config.yaml contains:
```
## test.obo
  - id: test
    preferredPrefix: test
    title: Test ontology
    uri: http://example.com/ontology/test.obo
    description: "Test short description"
    base_uri:
      - http://example.com/ontology/test/test_
    oboSlims: false
    ontology_purl : http://example.com/ontology/test.obo
```

Once the ontology is loaded and indexed, I access to the internal OLS web and in the "Ontology info" box the "Ontology IRI" is set to "Ontology IRI: http://purl.obolibrary.org/obo/test", which I would expect it to be http://example.com/ontology/test.obo. This IRI change happens when I run the indexer.

Additionally, the "Ontology info" box also says that I have 306 terms, however I cannot see any term if I click "Terms" button, but if I search one in the box above it list the terms. This occurs because the IRI is wrong, or it has nothing to do with it?

Thank you,
José Antonio
