### ISSUE TITLE
Index a big ontology under the same identifier

### ISSUE THREAD

**Issue by neobernad** [EBISPOT/OLS#251]
Hello,

I split a big OBO ontology (~30GB) into smaller chunks so that my server has enough memory to index them into OLS. The problem is that since there are several files, in the `ols-config.yaml` file I have to create an entry per each file:
```
  - id: split_0
    preferredPrefix: OriginalTitle
    title: Title
    uri: http://example.com/split
    description: "Desc"
    base_uri:
      - http://example.com/split#
    ontology_purl : 
      - http://example.com/split_0.obo

  - id: split_1
    preferredPrefix: OriginalTitle
    title: Title
    uri: http://example.com/split
    description: "Desc"
    base_uri:
      - http://example.com/split#
    ontology_purl : 
      - http://example.com/split_1.obo
.
.
.
```
Additionally, due to an OWL API bug (https://github.com/EBISPOT/OLS/issues/242) the IRIs are generated as http://purl.obolibrary.org/obo/split_0 and http://purl.obolibrary.org/obo/split_1 instead of http://example.com/split, thus terms appear in different URIs.

I would like them to be shown as an unique OBO file and under the same URI, instead of several ones, is that possible?

Thanks,
José Antonio
