### ISSUE TITLE
Feature request: ability to add a logo

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#452]
NOt a priority, but it'd be nice to have the option to add a logo on the ontology page. Eg for GECKO at https://www.ebi.ac.uk/ols/ontologies/gecko I'd like to display 
![GECKO_logo_2021](https://user-images.githubusercontent.com/2214135/105184315-1fc83a00-5b27-11eb-94d8-525bab7becba.png)

**Comment by matentzn** [comment]
That would be great! Also for SNOMED, MONDO, HPO etc - they would all love that.

As an aside: I am loving the G in the new GECKO logo!!! I didnt even notice that before! Extremely cool!

**Comment by matentzn** [comment]
should be an option in ontology config, the option being `ontology_logo:` and the value being a URL (test https and HTTP).

**Comment by udp** [comment]
In 3.x-dev branch

**Comment by matentzn** [comment]
This ols-config.yaml does not work for me:

```
'@context': null
ontologies:
- base_uri:
  - https://purl.ihccglobal.org/CHOP_
  description: Data elements collected by CHOP to develop the Philadelphia Neurodevelopmental
    Cohort (PNC) plus data developed with the University of Pennsylvania on Alzheimer's
    susceptibility
  id: chop
  ontology_purl: https://raw.githubusercontent.com/IHCC-cohorts/data-harmonization/master/data_dictionaries/chop.owl
  preferredPrefix: CHOP
  logo: https://user-images.githubusercontent.com/2214135/105184315-1fc83a00-5b27-11eb-94d8-525bab7becba.png
  title: Center for Applied Genomics, Children's Hospital of Philadelphia
```

Neither is there a logo, no an HTML element with a logo generated? Any idea what could be wrong?
