### ISSUE TITLE
Add PRIDE, PSI-MS & PSI-MOD

### ISSUE THREAD

**Issue by Tobias-Ternent** [EBISPOT/OLS#46]
I had a look at the new OLS beta and I didn't see that the following 3 ontologies were listed. Please could you include them?

PRIDE
https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride_cv.obo
or I've got this in OWL format if you'd prefer:
https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride_cv.owl

PSI-MS
https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo

PSI-MOD
https://raw.githubusercontent.com/MICommunity/psidev/master/psi/mod/data/PSI-MOD.obo

**Comment by simonjupp** [comment]
PRIDE I can add. I'm confused about the other two. We get most of our ontologies from OBO foundry. 

We load MS from https://raw.githubusercontent.com/MICommunity/psidev/master/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo, which we get from OBO foundry http://obofoundry.github.io/ontology/ms.html, is this the same as PSI-MS? Seems the location is different from https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo

We also have MOD in OLS, coming from https://raw.githubusercontent.com/MICommunity/psidev/master/psi/mod/data/PSI-MOD.obo, meta data is here http://obofoundry.github.io/ontology/mod.html. This does seem to be the same file you specified.

**Comment by Tobias-Ternent** [comment]
Great, thanks Simon for planning to add PRIDE, and clarification about PSI-MOD.

Yes, PSI-MS is the same as MS. The new home for PSI-MS is a repo directly under HUPO-PSI:
https://github.com/HUPO-PSI/psi-ms-CV
Which is up-to-date:
format-version: 1.2
data-version: 3.82.0
date: 06:01:2016 14:40

Whereas the MICommunity/psidev/master/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo is out of date:
format-version: 1.2
date: 30:05:2014 00:48

@germa please could you update the listing for PSI-MS on http://obofoundry.github.io/ontology/ms.html ?

**Comment by simonjupp** [comment]
OK, so create a pull request to change the source of  http://obofoundry.github.io/ontology/ms.html and OLS should pick it up within 24 hours.

**Comment by simonjupp** [comment]
I had a problem loading the PRIDE OWL file see PRIDE-Utilities/pride-ontology#1

This is the configuration I have for PRIDE to load into new OLS. Can you check the description as I just took something off the PRIDE homepage, would be better to tailor it to describe the ontology. Also, what is the best way to contact the developers? Do you have a mailing list or should I point at the github issue tracker?

```
## PRIDE ontology

  - id: pride
    preferredPrefix: PRIDE
    title: PRIDE Controlled Vocabulary
    uri: http://purl.obolibrary.org/obo/pride_cv.obo
    description: "The PRIDE PRoteomics IDEntifications (PRIDE) database is a centralized, standards compliant, public data repository for proteomics data, including protein and peptide identifications, post-translational modifications and supporting spectral evidence."
    homepage: https://github.com/PRIDE-Utilities/pride-ontology
    mailing_list: https://github.com/PRIDE-Utilities/pride-ontology/issues
    definition_property:
      - http://purl.obolibrary.org/obo/def
    synonym_property:
      - http://www.geneontology.org/formats/oboInOWL#hasExactSynonym
    base_uri:
      - http://purl.obolibrary.org/obo/PRIDE_
    hierarchical_property:
      - http://purl.obolibrary.org/obo/pride_cv.obo#part_of
    oboSlims: false
    ontology_purl : https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride_cv.obo
```
