### ISSUE TITLE
Ontology description/label beats ols-config.yaml?

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#472]
In my ols config, I have:

```
- id: hp
    preferredPrefix: HP
    title: Human Phenotype Ontology (Development Snapshot)
    uri: http://purl.obolibrary.org/obo/hp.owl
    description: >
      Inofficial development snapshot of the Human Phenotype Ontologies. Contact Peter Robinson.
    base_uri:
      - http://purl.obolibrary.org/obo/HP_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
#    label_property:  http://www.w3.org/2004/02/skos/core#prefLabel
    reasoner: EL
    oboSlims: false
    ontology_purl : file:/opt/ols/ontologies/hp.owl
```

But it shows up as:
https://ols.monarchinitiative.org/ontologies/hp

I think that was not the case until recently. Config should trump ontology annotations!
