### ISSUE TITLE
How to load multiple files into one ontology?

### ISSUE THREAD

**Issue by KonradHoeffner** [EBISPOT/OLS#633]
I am trying to import the [RDFBones ontology](https://github.com/RDFBones/RDFBones-O), which consists of 6 owl files that belong to the same ontology (graph).
All 6 files are included under the 'products' key in `config/ols-config.yaml`. However it seems as if OLS only loads `RDFBones-main` and none of the others.
How can I get OLS to load all 6 files?

```yaml
"@context":

ontologies:
[...]
- activity_status: active
  description: The RDFBones core ontology for osteological research data from anthropological investigations.
  homepage: https://github.com/RDFBones/RDFBones-O
  id: bones
  layout: ontology_detail
  ontology_purl: https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/RDFBones-main.owl
  products:
    - {id: RDFBones-main.owl, ontology_purl: 'https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/RDFBonesSubset.owl'}
    - {id: CIDOC-CRM-RDFBonesSubset.owl, ontology_purl: 'https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/CIDOC-CRM-RDFBonesSubset.owl'}
    - {id: FMA-RDFBonesSubset.owl, ontology_purl: 'https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/FMA-RDFBonesSubset.owl'}
    - {id: OBI-RDFBonesSubset.owl, ontology_purl: 'https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/OBI-RDFBonesSubset.owl'}
    - {id: RDFBones-RIOs-EntireBoneOrgan.owl, ontology_purl: 'https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/RDFBones-RIOs-EntireBoneOrgan.owl'}
    - {id: SIO-RDFBonesSubset.owl, ontology_purl: 'https://raw.githubusercontent.com/RDFBones/RDFBones-O/master/SIO-RDFBonesSubset.owl'}
  title: RDF Bones
  tracker: https://github.com/RDFBones/RDFBones-O
```
