### ISSUE TITLE
search ignores properties that are not configured as hidden

### ISSUE THREAD

**Issue by KonradHoeffner** [EBISPOT/OLS#649]
In `ols-config.yaml` I have not set any value for "hidden_property".
The search index is generated as part of the general Docker setup, all volumes have been cleared with "docker compose down -v" before "docker compose up" and it has been built too.
I thus assume that *all* properties of my ontology are included in the search index.
However in practice, several of my properties are just ignored by the search:

```xml
    <owl:Class rdf:about="https://ols.imise.uni-leipzig.de/ontologies/anno#Eminence">
        <rdfs:subClassOf rdf:resource="https://ols.imise.uni-leipzig.de/ontologies/anno#Elevation"/>
        <rdfs:comment>Standring (2016): less often applied to certain bony projections;

Adj. Der Defintionen tw. Widersprüchlich</rdfs:comment>
        <skos:altLabel>- (de)</skos:altLabel>
        <rdfs:label >Eminence</rdfs:label>
        <skos:altLabel>Eminentia (la)</skos:altLabel>
        <association_with_other_terms>Ähnliche Strukturen:
Tubeculum, Processus, tuber, tuberositas 

Protuberance, prominence, torus</association_with_other_terms>
        <characteristic_features_all_languages>länglich, elongated, rounded, less prominent than a process, small</characteristic_features_all_languages>
        <definition>eher länglicher Knochenhöcker, Vorsprung, Höcker tjongtijö (de)</definition>
        <definition >elevation / bony projection, usually not as / less prominent as / than  a process; rounded bulge; elongated protuberance; small projection or bump (Wiki/Internet)</definition>
        <definition_from_literature_by_ref_bass_2005_>-</definition_from_literature_by_ref_bass_2005_>
        <definition_from_literature_by_ref_burns_2012_>-</definition_from_literature_by_ref_burns_2012_>
        <definition_from_literature_by_ref_christensen_et_al_2014_>Projections</definition_from_literature_by_ref_christensen_et_al_2014_>
        <definition_from_literature_by_ref_dauber_feneis_2008_>ja</definition_from_literature_by_ref_dauber_feneis_2008_>
        <definition_from_literature_by_ref_fipat_tanthro_>Projections &amp; Parts</definition_from_literature_by_ref_fipat_tanthro_>
        <definition_from_literature_by_ref_matshes_2005_>Terms involving raised areas on the surface of bones.</definition_from_literature_by_ref_matshes_2005_>
        <definition_from_literature_by_ref_standring_2016_>projection</definition_from_literature_by_ref_standring_2016_>
        <definition_from_literature_by_ref_white_2012_>Projections &amp; Parts</definition_from_literature_by_ref_white_2012_>
        <described_by_other_terms>protuberance, elevation, projection, bulge</described_by_other_terms>
        <id>LA010</id>
        <kind_of_association>Standring (2016):  The terms protuberance, promi­nence,  eminence  and  torus  are  less  often  applied  to  certain  bony 
 projections.</kind_of_association>
        <used_as_a_descriptive_for_other_terms>Tuberositas , Tuberculum, Caput, Capitulum, Condylus</used_as_a_descriptive_for_other_terms>
    </owl:Class>
```

For example, I get 0 results for the term "Standring", which is included both in "rdfs:comment" and in "kind_of_association".

P.S.: Search in synonyms (configured as skos:altLabel) does not work as well.

## ols-config.yml

```yaml
ontologies:
- activity_status: active
  contact: [...]
  description: ANNO is an ontology for anthropological notation
  homepage: https://annosaxfdm.de
  id: anno
  layout: ontology_detail
  synonym_property:
    - http://www.w3.org/2004/02/skos/core#altLabel
  # label seems to be ignored as synonym property
    - http://www.w3.org/2000/01/rdf-schema#label
  definition_property:
    - https://ols.imise.uni-leipzig.de/ontologies/anno#definition
  ontology_purl: file:///ontology/anno-ols.owl
  products:
    - {id: anno.owl, ontology_purl: 'file:///ontology/anno.owl'}
  title: The Anthropological Notation Ontology
  tracker: https://github.com/annosaxfdm/ols
  preferred_root_term:
    - https://www.imise.uni-leipzig.de/ontologies/anno#Anatomical_location
    - https://www.imise.uni-leipzig.de/ontologies/anno#Bone
```
